INSERT INTO DISCIPLINA (NOME) VALUES ('Português');
INSERT INTO DISCIPLINA (NOME) VALUES ('Matemática');
INSERT INTO DISCIPLINA (NOME) VALUES ('História');
INSERT INTO DISCIPLINA (NOME) VALUES ('Filosofia');
INSERT INTO DISCIPLINA (NOME) VALUES ('Biologia');
INSERT INTO DISCIPLINA (NOME) VALUES ('Física');
INSERT INTO DISCIPLINA (NOME) VALUES ('Química');
INSERT INTO DISCIPLINA (NOME) VALUES ('Geografia');