CREATE TABLE ROLE
(  
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ROLE_NAME VARCHAR(255) NOT NULL
 ); 

CREATE TABLE USER
(  
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
 ); 