CREATE TABLE USER
(  
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_NAME VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  SALT VARCHAR(255) NOT NULL,
  PRIMEIRO_LOGIN BOOLEAN DEFAULT TRUE
 );

CREATE TABLE ESTUDANTE
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_COMPLETO VARCHAR(255) NOT NULL,
  DATA_NASCIMENTO DATETIME,
  NOME_MAE VARCHAR(255) NOT NULL,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE INSTRUTOR
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_COMPLETO VARCHAR(255) NOT NULL,
  DATA_NASCIMENTO DATETIME,
  CPF VARCHAR(14) NOT NULL,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE DISCIPLINA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
);

CREATE TABLE INSTRUTOR_DISCIPLINA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  INSTRUTOR_ID INT NOT NULL,
  DISCIPLINA_ID INT NOT NULL,
  FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTOR(ID),
  FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(ID)
);

CREATE TABLE ESTUDANTE_DISCIPLINA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ESTUDANTE_ID INT NOT NULL,
  DISCIPLINA_ID INT NOT NULL,
  FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE(ID),
  FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(ID)
);

CREATE TABLE AULA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  INSTRUTOR_ID INT NOT NULL,
  DISCIPLINA_ID INT NOT NULL,
  DATA_INICIO DATETIME,
  DATA_FIM DATETIME,
  FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTOR(ID),
  FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(ID)
);

CREATE TABLE DOCUMENTO_AULA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AULA_ID INT NOT NULL,
  NOME_ORGINAL VARCHAR(255),
  EXTENSAO_ORIGINAL VARCHAR(255),
  CAMINHO_DOCUMENTO VARCHAR(255),
  FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);

CREATE TABLE FREQUENCIA_AULA
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AULA_ID INT NOT NULL,
  ESTUDANTE_ID INT NOT NULL,
  PARTICIPOU BOOLEAN,
  FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE(ID),
  FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);