@startuml
class AllowedExtensionsAttribute {
    + AllowedExtensionsAttribute(extensions:string[])
    # <<override>> IsValid(value:object, validationContext:ValidationContext) : ValidationResult
    + {static} GetErrorMessage() : string
}
ValidationAttribute <|-- AllowedExtensionsAttribute
@enduml
