@startuml
class FileHelperService {
    - <<readonly>> dirPath : string
    + FileHelperService(environment:IHostEnvironment, uow:IUnitOfWork)
    + <<async>> GetSingleFileAsync(documentoId:long) : Task<(string, byte[])>
    - {static} <<async>> GetSingleFileAsync(arquivo:DocumentoAula) : Task<byte[]>
    + <<async>> SaveFileAsync(fileDTO:FileDTO) : Task<string>
    - GetFullPath() : string
    + <<async>> DeleteFile(documentoId:long) : Task
    - {static} DeleteFile(caminhoArquivo:string) : void
    + <<async>> GetDocumentoAula(aulaId:long) : Task<DocumentoAulaDTO>
}
IFileHelperService <|-- FileHelperService
FileHelperService --> "_environment" IHostEnvironment
FileHelperService --> "_uow" IUnitOfWork
@enduml
