@startuml
interface IDisciplinaRepository {
    GetDisciplinasPorInstrutor(instrutorId:long) : List<Disciplina>
    GetDisciplinasPorEstudante(estudanteId:long) : List<Disciplina>
}
class "IBaseRepository"<T> {
}
"IBaseRepository" "<Disciplina>" <|-- IDisciplinaRepository
@enduml
