@startuml
interface IInstrutorDisciplinaRepository {
    + InserirDisplicinasDoInstrutor(instrutorDisciplinasList:List<InstrutorDisciplina>) : Task<bool>
}
class "IBaseRepository"<T> {
}
"IBaseRepository" "<InstrutorDisciplina>" <|-- IInstrutorDisciplinaRepository
@enduml
