@startuml
class DisciplinaMap {
    + Configure(builder:EntityTypeBuilder<Disciplina>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Disciplina>" <|-- DisciplinaMap
@enduml
