@startuml
class EstudanteMap {
    + Configure(builder:EntityTypeBuilder<Estudante>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Estudante>" <|-- EstudanteMap
@enduml
