@startuml
class EstudanteDisciplinaMap {
    + Configure(builder:EntityTypeBuilder<EstudanteDisciplina>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<EstudanteDisciplina>" <|-- EstudanteDisciplinaMap
@enduml
