@startuml
class InstrutorMap {
    + Configure(builder:EntityTypeBuilder<Instrutor>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Instrutor>" <|-- InstrutorMap
@enduml
