@startuml
class InstrutorDisciplinaMap {
    + Configure(builder:EntityTypeBuilder<InstrutorDisciplina>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<InstrutorDisciplina>" <|-- InstrutorDisciplinaMap
@enduml
